mongodb:
    url: mongodb://diegodamato:qwe951as@ds139322.mlab.com:39322/desafio

server:
  port: 3000
log:
  path: log
  maxSize: 100000
  maxFiles: 10
  files:
    erro: desafio-erro.log
    info: desafio-info.log


